apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dex-grpc-client-cert
  namespace: jx-staging
spec:
  secretName: dex-grpc-client-cert
  issuerRef:
    name: dex-grpc-issuer
    kind: ClusterIssuer
  commonName: dex-grpc-client
  dnsName:
  - dex
