apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dex-cert
  namespace: jx-staging
spec:
  secretName: dex-tls
  issuerRef: 
    name: letsencrypt-staging
  commonName: '*.jxstaging.org'
  dnsName:
    - jxstaging.org
  acme:
    config:
    - dns01: 
        provider: prod-dns
      domains:
      - '*.jxstaging.org'
