apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dex-staging
  namespace: jx-staging
spec:
  secretName: dex-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: jxstaging.org
  dnsName:
  - www.jxstaging.org
  acme:
    config:
    - http01:
        ingressClass: nginx
      domain:
      - jxstaging.org
